- name: 'Keymap : Change keymap'
  lineinfile:
    dest: /etc/vconsole.conf
    line: KEYMAP=jp106
    regexp: ^#?\s*KEYMAP=jp106
    create: yes
  register: change_keymap

- name: 'Keymap : Load keymap'
  command: loadkeys jp106
  when: change_keymap|changed
