#- import_tasks: ipv6.yml
#- import_tasks: system.yml
#- import_tasks: hostname.yml
#- import_tasks: lcd.yml
#- import_tasks: locale.yml
#- import_tasks: timezone.yml
#- import_tasks: keyboard.yml

- import_tasks: rds/main.yml

##- import_tasks: package.yml
#- import_tasks: soracom.yml
##- import_tasks: wifi.yml


