#- import_tasks: system.yml  # first task
#- import_tasks: package.yml
#- import_tasks: raspi-config/main.yml
#- import_tasks: hostname.yml
#- import_tasks: sudo.yml
#- import_tasks: keymap.yml
#- import_tasks: wifi.yml
#- import_tasks: soracom.yml


#- import_tasks: system.yml  # first task
#- import_tasks: hostname.yml
- import_tasks: keyboard.yml
#- import_tasks: lcd.yml
#- import_tasks: locale.yml
##- import_tasks: package.yml
#- import_tasks: soracom.yml
##- import_tasks: sudo.yml
- import_tasks: timezone.yml
##- import_tasks: wifi.yml
