- name: 'Sudo : Install sudo'
  pacman:
    name: sudo

- name: 'Sudo : sudoers defaults'
  template:
    src: sudo/defaults.j2
    dest: /etc/sudoers.d/defaults
    owner: root
    group: root
    mode: 0440

- name: 'Sudo : sudoers wheel'
  template:
    src: sudo/wheel.j2
    dest: /etc/sudoers.d/wheel
    owner: root
    group: root
    mode: 0440
