- name: 'Timezone : Update configuration'
  debconf:
    name: tzdata
    question: '{{ item.key }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  become: yes
  with_items: '{{ RASPBERRYPI_TIMEZONE }}'
