- name: Install package
  pacman:
    name: '{{ item }}'
  with_items:
    #- dnsmasq
    - hostapd

#- name: Configure udev
#  become: yes
#  template:
#    src: soracom/40-ak-020.rules.j2
#    dest: /etc/udev/rules.d/40-ak-020.rules
#    owner: root
#    group: root
#    mode: 0644
#
#- name: Configure wvdial
#  become: yes
#  template:
#    src: soracom/wvdial.conf.j2
#    dest: /etc/wvdial.conf
#    owner: root
#    group: root
#    mode: 0644
#
#- name: Configure PPP
#  become: yes
#  template:
#    src: soracom/wvdial.j2
#    dest: /etc/ppp/peers/wvdial
#    owner: root
#    group: root
#    mode: 0644
