- name: 'raspi-config : Get 1-Wire'
  command: raspi-config nonint get_onewire
  register: get_onewire
  become: yes
  changed_when: no

- name: 'raspi-config : Enable 1-Wire'
  command: raspi-config nonint do_onewire {{ RASPBERRYPI_1WIRE_ENABLE }}
  become: yes
  when: get_onewire.stdout | int != RASPBERRYPI_1WIRE_ENABLE
