- name: 'raspi-config : Get camera'
  command: raspi-config nonint get_camera
  register: get_camera
  become: yes
  changed_when: no

- name: 'raspi-config : Enable camera'
  command: raspi-config nonint do_camera {{ RASPBERRYPI_CAMERA_ENABLE }}
  become: yes
  when: get_camera.stdout | int != RASPBERRYPI_CAMERA_ENABLE
