- name: 'raspi-config : Get Remote GPIO'
  command: raspi-config nonint get_rgpio
  register: get_rgpio
  become: yes
  changed_when: no

- name: 'raspi-config : Enable Remote GPIO'
  command: raspi-config nonint do_rgpio {{ RASPBERRYPI_RGPIO_ENABLE }}
  when: get_rgpio.stdout | int != RASPBERRYPI_RGPIO_ENABLE
