- name: 'raspi-config : Get SPI'
  command: raspi-config nonint get_spi
  register: get_spi
  become: yes
  changed_when: no

- name: 'raspi-config : Enable SPI'
  command: raspi-config nonint do_spi {{ RASPBERRYPI_SPI_ENABLE }}
  become: yes
  when: get_spi.stdout | int != RASPBERRYPI_SPI_ENABLE
