- name: 'raspi-config : Get VNC'
  command: raspi-config nonint get_vnc
  register: get_vnc
  become: yes
  changed_when: no

- name: 'raspi-config : Enable VNC'
  command: raspi-config nonint do_vnc {{ RASPBERRYPI_VNC_ENABLE }}
  become: yes
  when: get_vnc.stdout | int != RASPBERRYPI_VNC_ENABLE
